### ISSUE TITLE
"Rate Limit reached" on valid OpenAI account

### ISSUE THREAD

**Issue by romanr** [Blarc/ai-commits-intellij-plugin#93]
Plugin thinks about 30 sec and then outputs:

```
Error occurred: Rate limit reached for default-gpt-3.5-turbo in organization org-qhdxxxxslxlioFX7inZ on tokens per min. Limit: 90000 / min. Current: 0 / min. Contact us through our help center at help.openai.com if you continue to have issues.
```
Tryied different prompts - same result.
OpenAI account  uses pay as you go billing, and works fine with any other intgration.

**Comment by krrishdholakia** [comment]
Hey @romanr if you're able create multiple azure embedding instances - you could use LiteLLM's openai-compatible server  to loadbalance across from them: 

**Step 1: Put your instances in a `config.yaml`**
```yaml
model_list:
  - model_name: zephyr-beta
    litellm_params:
        model: huggingface/HuggingFaceH4/zephyr-7b-beta
        api_base: http://0.0.0.0:8001
  - model_name: zephyr-beta
    litellm_params:
        model: huggingface/HuggingFaceH4/zephyr-7b-beta
        api_base: http://0.0.0.0:8002
  - model_name: zephyr-beta
    litellm_params:
        model: huggingface/HuggingFaceH4/zephyr-7b-beta
        api_base: http://0.0.0.0:8003
```

**Step 2: Install LiteLLM**

```bash
$ pip install litellm
```

**Step 3: Start litellm proxy w/ config.yaml**

```bash
$ litellm --config /path/to/config.yaml
```

Docs: https://docs.litellm.ai/docs/simple_proxy
